#!/usr/bin/env python3
"""Gather per-module docs.md into the Jekyll site.

Walks src/{agentic,tools,harnesses}/<module>/docs.md and emits, into the site
source directory:

  modules/<area>/<name>.md   one page per module that has a docs.md
  modules/index.md           the /modules index
  _data/modules.yml          nav + index data

A module without a docs.md produces no page and no data entry.
"""
import argparse
import json
import re
import sys
from pathlib import Path
from typing import NoReturn

AREAS = ("agentic", "tools", "harnesses")
AREA_LABELS = {"agentic": "Agentic", "tools": "Tools", "harnesses": "Harnesses"}
CAPABILITY_KEYS = ("agents", "commands", "skills", "hooks", "plugins", "tools", "mcps")
# (row label, singular, plural) per capability kind.
CAPABILITY_LABELS = {
    "agents": ("Agent", "agent", "agents"),
    "commands": ("Command", "command", "commands"),
    "skills": ("Skill", "skill", "skills"),
    "hooks": ("Hook", "hook", "hooks"),
    "plugins": ("Plugin", "plugin", "plugins"),
    "tools": ("Tool", "tool", "tools"),
    "mcps": ("MCP", "MCP", "MCPs"),
}
FM_LINE = re.compile(r"^([A-Za-z0-9_-]+):\s?(.*)$")
GENERATED_NOTE = "<!-- Generated by gather-module-docs — do not edit. -->"
TEMPLATES_DIR = Path(__file__).resolve().parent / "templates"
AGGREGATE_PAGES = (
    "agents.md",
    "skills.md",
    "commands.md",
    "hooks.md",
    "mcps.md",
    "module-reference.md",
)
# A pipe in a cell would split the column; a newline would break the row.
CELL_TRANSLATION = str.maketrans({"|": "\\|", "\n": " "})
# The semantic hook-event vocabulary and what each event means. This is the
# adapter contract, not module data — the backing modules are derived.
HOOK_EVENT_MEANINGS = {
    "file.edited": "A file was saved",
    "command.before": "A shell command is about to run (bash or a PTY invocation)",
    "command.after": "A shell command finished",
    "session.idle": "The session went quiet",
    "session.created": "A session started",
    "session.error": "A transient provider error",
}
# Front matter accepts only scalars, `[a, b]` flow lists and one level of
# `name: purpose` nesting. A block scalar would be read as its own indicator
# and a block sequence silently dropped, so both fail loudly instead.
BLOCK_SCALAR = re.compile(r"^[>|][+-]?$")


def _error(msg) -> NoReturn:
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def _unquote(value):
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    return value


def _parse_value(raw):
    """A scalar, or a YAML flow list (`[a, b]`)."""
    raw = raw.strip()
    if raw.startswith("[") and raw.endswith("]"):
        inner = raw[1:-1].strip()
        return [_unquote(item) for item in inner.split(",")] if inner else []
    return _unquote(raw)


def _as_list(value):
    if isinstance(value, dict):
        return list(value.keys())
    if isinstance(value, list):
        return value
    return [value] if value else []


def bare_name(name):
    return name.split(":", 1)[1] if ":" in name else name


def read_scalar(path, key):
    """Read one scalar from front matter or a `#`-comment header; else None."""
    pattern = re.compile(r"^#?\s*" + re.escape(key) + r":\s*(.*)$")
    try:
        with path.open(encoding="utf-8") as handle:
            for _ in range(25):
                line = handle.readline()
                if not line:
                    break
                match = pattern.match(line.strip())
                if match:
                    return _unquote(match.group(1))
    except OSError:
        pass
    return None


def read_json(path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


def capability_entries(meta, kind):
    """(names, purpose overrides) declared for one capability kind.

    A list declares names only (purposes are derived from the module files);
    a map declares names and their purpose.
    """
    value = meta.get(kind)
    if isinstance(value, dict):
        return list(value.keys()), value
    return _as_list(value), {}


def capability_details(root, area, name, meta):
    """Derive each capability's purpose from the module's own files."""
    base = root / "src" / area / name
    details = {kind: {} for kind in CAPABILITY_KEYS}

    skill_files = sorted(base.glob("skills/*/SKILL.md")) + sorted(base.glob("skills/SKILL.md"))
    for skill_md in skill_files:
        skill_name = read_scalar(skill_md, "name") or skill_md.parent.name
        details["skills"][bare_name(skill_name)] = read_scalar(skill_md, "description") or ""

    for agent_md in sorted(base.glob("agents/*.md")):
        details["agents"][agent_md.stem.lower()] = read_scalar(agent_md, "description") or ""
    for command_md in sorted(base.glob("commands/*.md")):
        details["commands"][command_md.stem] = read_scalar(command_md, "description") or ""

    for hook in (read_json(base / "hooks.json") or {}).get("hooks", []):
        if hook.get("id"):
            details["hooks"][hook["id"]] = hook.get("event", "")

    for server in (read_json(base / "mcp.json") or {}).get("mcp", {}):
        details["mcps"][server] = ""

    if (base / "tools").is_dir():
        for entry in sorted((base / "tools").iterdir()):
            if entry.name.startswith((".", "__")):
                continue  # caches and editor droppings are not tools
            if entry.is_file():
                details["tools"][entry.name.split(".")[0]] = read_scalar(entry, "description") or ""
            elif entry.is_dir():
                wrappers = sorted(entry.glob("*.mcp.sh"))
                if wrappers:
                    name = wrappers[0].name[: -len(".mcp.sh")]
                    details["tools"][name] = read_scalar(wrappers[0], "description") or ""
                elif any(entry.glob("*.sh")) or any(entry.glob("*.py")) or any(entry.glob("*.ts")):
                    details["tools"][entry.name] = ""
                # else: a data-only directory (the generator's templates/) is not a tool

    plugins = read_json(base / "plugin.opencode.json")
    if isinstance(plugins, (list, dict)):
        for plugin in plugins:
            if isinstance(plugin, str):
                details["plugins"][plugin] = ""

    return details


def capability_summary(capabilities):
    parts = []
    for kind in CAPABILITY_KEYS:
        count = len(capabilities.get(kind, []))
        if not count:
            continue
        _, singular, plural = CAPABILITY_LABELS[kind]
        parts.append(f"{count} {singular if count == 1 else plural}")
    return " · ".join(parts)


def render_contents(module):
    capabilities = module.get("capabilities") or {}
    overrides = module.get("overrides") or {}
    details = module.get("details") or {}
    rows = []
    for kind in CAPABILITY_KEYS:
        label = CAPABILITY_LABELS[kind][0]
        for name in capabilities.get(kind, []):
            purpose = (
                overrides.get(kind, {}).get(name)
                or details.get(kind, {}).get(bare_name(name))
                or ""
            )
            rows.append(f"| {label} | `{cell(name)}` | {cell(purpose) or '—'} |")
    if not rows:
        return ""
    header = ["## Contents", "", "| Type | Name | Purpose |", "| --- | --- | --- |"]
    return "\n".join(header + rows) + "\n"


def insert_contents(body, section):
    if not section:
        return body
    match = re.search(r"^##\s+Configuration\s*$", body, re.MULTILINE)
    if match:
        return body[: match.start()] + section + "\n" + body[match.start():]
    return body.rstrip() + "\n\n" + section


def cell(text):
    return (text or "").translate(CELL_TRANSLATION).strip()


def count_cell(value):
    return str(value) if value else "—"


def markdown_table(header, rows):
    if not rows:
        return "_None._"
    lines = [
        "| " + " | ".join(header) + " |",
        "| " + " | ".join(["---"] * len(header)) + " |",
    ]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    return "\n".join(lines)


def module_link(area, name, documented):
    return f"[{name}](/modules/{area}/{name})" if documented else f"`{name}`"


def mcp_tool_entries(root, area, name):
    """The `*.mcp.sh` tools a module exposes through the devbot-tools server."""
    tools_dir = root / "src" / area / name / "tools"
    if not tools_dir.is_dir():
        return []
    return [
        (path.name[: -len(".mcp.sh")], read_scalar(path, "description") or "")
        for path in sorted(tools_dir.rglob("*.mcp.sh"))
    ]


def collect_inventory(root):
    inventory = []
    for area in AREAS:
        area_dir = root / "src" / area
        if not area_dir.is_dir():
            continue
        for module_dir in sorted(p for p in area_dir.iterdir() if p.is_dir()):
            doc = module_dir / "docs.md"
            meta = {}
            if doc.is_file():
                meta, _ = parse_front_matter(doc.read_text(encoding="utf-8"), doc)
            declared = {}
            for key in CAPABILITY_KEYS:
                names, _ = capability_entries(meta, key)
                if names:
                    declared[key] = names
            inventory.append({
                "name": module_dir.name,
                "area": area,
                "documented": doc.is_file(),
                "description": meta.get("description") or "",
                "declared": declared,
                "details": capability_details(root, area, module_dir.name, meta),
                "mcp_purposes": meta.get("mcps") if isinstance(meta.get("mcps"), dict) else {},
            })
    return inventory


def agent_mode(root, area, name, agent):
    path = root / "src" / area / name / "agents" / f"{agent}.md"
    return read_scalar(path, "mode") or "subagent"


def render_agent_tree(root, inventory):
    """The on-disk agent layout, derived so it cannot drift from the tables."""
    lines = []
    for entry in inventory:
        agents = sorted(entry["declared"].get("agents", []))
        if not agents:
            continue
        lines.append(f"src/{entry['area']}/{entry['name']}/agents/")
        for agent in agents:
            mode = agent_mode(root, entry["area"], entry["name"], agent)
            description = entry["details"]["agents"].get(agent, "")
            title = description.split(" — ")[0].strip() if " — " in description else agent
            suffix = " (primary)" if mode == "primary" else ""
            lines.append(f"  {agent}.md — {title}{suffix}")
        lines.append("")
    return "```\n" + "\n".join(lines).rstrip() + "\n```"


def aggregate_tables(root, inventory):
    primary, subagents = [], []
    skills, commands, hooks, mcps, mcp_tools = [], [], [], [], []
    internal, tools_modules = [], []
    events = {}

    for entry in inventory:
        # A module without a docs.md gets no page and no reference anywhere on
        # the site — the aggregates included.
        if not entry["documented"]:
            continue
        area, name, details = entry["area"], entry["name"], entry["details"]
        link = module_link(area, name, entry["documented"])
        purposes = entry["mcp_purposes"]
        # One capability set feeds every generated view: the module's declared
        # manifest. Deriving here too is what keeps the index, the page
        # Contents and these tables in step.
        capabilities = entry["declared"]

        for agent in capabilities.get("agents", []):
            row = [f"`{agent}`", link, cell(details["agents"].get(agent, ""))]
            if agent_mode(root, area, name, agent) == "primary":
                primary.append(row)
            else:
                subagents.append(row)

        for skill in capabilities.get("skills", []):
            bare = bare_name(skill)
            skills.append([link, f"`devbot:{bare}`", cell(details["skills"].get(bare, ""))])
        for command in capabilities.get("commands", []):
            commands.append([link, f"`{command}`", cell(details["commands"].get(command, ""))])
        for hook in capabilities.get("hooks", []):
            event = details["hooks"].get(hook, "")
            hooks.append([link, f"`{hook}`", f"`{event}`" if event else "—"])
            if event in HOOK_EVENT_MEANINGS:
                events.setdefault(event, []).append(link)
        for server in capabilities.get("mcps", []):
            mcps.append([link, f"`{server}`", cell(purposes.get(server) or details["mcps"].get(server, ""))])
        declared_tools = set(capabilities.get("tools", []))
        for tool, description in mcp_tool_entries(root, area, name):
            if tool in declared_tools:
                mcp_tools.append([link, f"`{tool}`", cell(description)])

        counts = {key: len(capabilities.get(key, [])) for key in CAPABILITY_KEYS}
        row = [
            link,
            count_cell(counts["skills"]),
            count_cell(counts["tools"]),
            count_cell(counts["commands"]),
            count_cell(counts["agents"]),
            count_cell(counts["hooks"]),
            "✓" if counts["mcps"] else "—",
            cell(entry["description"]),
        ]
        if area == "agentic":
            internal.append(row)
        elif area == "tools":
            tools_modules.append(row)

    return {
        "AGENTS_PRIMARY": markdown_table(["Agent", "Module", "Description"], primary),
        "AGENTS_SUBAGENTS": markdown_table(["Agent", "Module", "Description"], subagents),
        "AGENT_TREE": render_agent_tree(root, inventory),
        "SEMANTIC_EVENTS": markdown_table(
            ["Event", "Meaning", "Modules"],
            [
                [f"`{event}`", meaning, ", ".join(events.get(event, [])) or "—"]
                for event, meaning in HOOK_EVENT_MEANINGS.items()
            ],
        ),
        "SKILLS": markdown_table(["Module", "Skill", "Description"], skills),
        "COMMANDS": markdown_table(["Module", "Command", "Description"], commands),
        "HOOKS": markdown_table(["Module", "Hook", "Event"], hooks),
        "MCPS": markdown_table(["Module", "MCP server", "Provides"], mcps),
        "MCP_TOOLS": markdown_table(["Module", "Tool", "Description"], mcp_tools),
        "MODULES_INTERNAL": markdown_table(
            ["Module", "S", "T", "C", "A", "H", "MCP", "Description"], internal
        ),
        "MODULES_TOOLS": markdown_table(
            ["Module", "S", "T", "C", "A", "H", "MCP", "Description"], tools_modules
        ),
    }


def write_aggregates(root, out):
    """Render the aggregate pages from their committed prose templates."""
    tables = aggregate_tables(root, collect_inventory(root))
    for page_name in AGGREGATE_PAGES:
        template = TEMPLATES_DIR / f"{page_name}.tpl"
        if not template.is_file():
            _error(f"missing aggregate template: {template}")
        text = template.read_text(encoding="utf-8")
        for marker, rendered in tables.items():
            text = text.replace(f"<!-- GENERATED:{marker} -->", rendered)
        (out / page_name).write_text(text, encoding="utf-8")


def parse_front_matter(text, path):
    """Minimal top-level `key: value` parser with one level of nesting."""
    if not text.startswith("---"):
        return {}, text
    parts = text.split("---", 2)
    if len(parts) < 3:
        _error(f"{path}: malformed front matter (missing closing ---)")

    meta, block = {}, None
    for raw in parts[1].splitlines():
        if not raw.strip():
            continue
        stripped = raw.strip()
        if stripped.startswith("- "):
            _error(
                f"{path}: unsupported YAML block sequence ({stripped!r}) — "
                "write the list inline as `key: [a, b]`"
            )
        if raw[0] in " \t":
            if block:
                match = FM_LINE.match(stripped)
                if match:
                    meta[block][match.group(1)] = _parse_value(match.group(2))
            continue
        match = FM_LINE.match(raw)
        if not match:
            continue
        key, value = match.group(1), match.group(2)
        if BLOCK_SCALAR.match(value.strip()):
            _error(
                f"{path}: unsupported YAML block scalar for `{key}` ({value.strip()!r}) — "
                "write it on a single line"
            )
        if value == "":
            block = key
            meta[key] = {}
        else:
            block = None
            meta[key] = _parse_value(value)
    return meta, parts[2].lstrip("\n")


def humanize(name):
    return name.replace("-", " ").replace("_", " ").title()


def yaml_string(value):
    # JSON strings are a valid subset of YAML strings — correct quoting for free.
    return json.dumps(value, ensure_ascii=False)


def collect(root):
    modules = []
    for area in AREAS:
        area_dir = root / "src" / area
        if not area_dir.is_dir():
            continue
        for module_dir in sorted(p for p in area_dir.iterdir() if p.is_dir()):
            doc = module_dir / "docs.md"
            if not doc.is_file():
                continue
            meta, body = parse_front_matter(doc.read_text(encoding="utf-8"), doc)
            description = meta.get("description")
            if not description:
                _error(f"{doc}: missing required 'description' front matter")
            capabilities, overrides = {}, {}
            for key in CAPABILITY_KEYS:
                names, purposes = capability_entries(meta, key)
                if names:
                    capabilities[key] = names
                    if purposes:
                        overrides[key] = purposes
            modules.append({
                "name": module_dir.name,
                "area": area,
                "area_label": AREA_LABELS[area],
                "title": meta.get("title") or humanize(module_dir.name),
                "description": description,
                "url": f"/modules/{area}/{module_dir.name}",
                "capabilities": capabilities,
                "overrides": overrides,
                "details": capability_details(root, area, module_dir.name, meta),
                "summary": capability_summary(capabilities),
                "body": body.rstrip() + "\n",
            })
    return modules


def render_page(module):
    front = [
        "---",
        "layout: page",
        f"title: {yaml_string(module['title'])}",
        f"description: {yaml_string(module['description'])}",
        "nav_section: docs",
        f"module_name: {module['name']}",
        f"module_area: {module['area']}",
        f"module_area_label: {yaml_string(module['area_label'])}",
    ]
    if module.get("summary"):
        front.append(f"capability_summary: {yaml_string(module['summary'])}")
    front.append("---")
    body = insert_contents(module["body"], render_contents(module))
    return "\n".join(front) + f"\n\n{GENERATED_NOTE}\n\n{body}"


def render_index(modules):
    counts = {area: [m for m in modules if m["area"] == area] for area in AREAS}
    jump = " · ".join(
        f"[{AREA_LABELS[area]} ({len(counts[area])})](#{area})"
        for area in AREAS
        if counts[area]
    )

    rows = [jump, ""]
    for area in AREAS:
        area_modules = sorted(counts[area], key=lambda m: m["name"])
        if not area_modules:
            continue
        rows.append(f"## {AREA_LABELS[area]}\n")
        rows.append("| Module | Description | Contains |")
        rows.append("| ------ | ----------- | -------- |")
        for module in area_modules:
            link = "{{ '" + module["url"] + "' | relative_url }}"
            rows.append(
                f"| [{cell(module['title'])}]({link}) | {cell(module['description'])}"
                f" | {cell(module.get('summary')) or '—'} |"
            )
        rows.append("")

    front = "\n".join([
        "---",
        "layout: page",
        'title: "Modules"',
        'description: "Every documented DevBot module."',
        "nav_section: docs",
        "nav_modules: true",
        "---",
    ])
    return f"{front}\n\n{GENERATED_NOTE}\n\n" + "\n".join(rows)


def render_data(modules):
    lines = ["# Generated by gather-module-docs — do not edit."]
    for module in modules:
        lines.append(f"- name: {yaml_string(module['name'])}")
        lines.append(f"  area: {yaml_string(module['area'])}")
        lines.append(f"  title: {yaml_string(module['title'])}")
        lines.append(f"  description: {yaml_string(module['description'])}")
        lines.append(f"  url: {yaml_string(module['url'])}")
        capabilities = module.get("capabilities") or {}
        if capabilities:
            lines.append("  capabilities:")
            for key in CAPABILITY_KEYS:
                if not capabilities.get(key):
                    continue
                lines.append(f"    {key}:")
                for item in capabilities[key]:
                    lines.append(f"      - {yaml_string(item)}")
    return "\n".join(lines) + "\n"


def prune(pages_dir, written):
    if not pages_dir.is_dir():
        return
    for stale in pages_dir.rglob("*.md"):
        if stale.resolve() not in written:
            stale.unlink()
    for directory in sorted(
        (p for p in pages_dir.rglob("*") if p.is_dir()), reverse=True
    ):
        if not any(directory.iterdir()):
            directory.rmdir()


def default_root():
    for parent in Path(__file__).resolve().parents:
        if (parent / "src" / "agentic").is_dir():
            return parent
    _error("could not locate the repo root — pass --root")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", help="repo root (default: auto-detected)")
    parser.add_argument("--out", help="site source dir (default: <root>/docs)")
    args = parser.parse_args()

    root = Path(args.root).resolve() if args.root else default_root()
    out = Path(args.out).resolve() if args.out else root / "docs"

    modules = collect(root)
    if not modules:
        print(
            "WARN: no module docs.md found under src/{agentic,tools,harnesses}/",
            file=sys.stderr,
        )

    written = set()
    for module in modules:
        page = out / "modules" / module["area"] / f"{module['name']}.md"
        page.parent.mkdir(parents=True, exist_ok=True)
        page.write_text(render_page(module), encoding="utf-8")
        written.add(page.resolve())

    index = out / "modules" / "index.md"
    index.parent.mkdir(parents=True, exist_ok=True)
    index.write_text(render_index(modules), encoding="utf-8")
    written.add(index.resolve())

    data = out / "_data" / "modules.yml"
    data.parent.mkdir(parents=True, exist_ok=True)
    data.write_text(render_data(modules), encoding="utf-8")

    prune(out / "modules", written)
    write_aggregates(root, out)
    print(f"gathered {len(modules)} module docs into {out}")


if __name__ == "__main__":
    main()
