#!/usr/bin/env python3
"""Gather per-module docs.md into the Jekyll site.

Walks src/{agentic,tools,harnesses}/<module>/docs.md and emits, into the site
source directory:

  modules/<area>/<name>.md   one page per module that has a docs.md
  modules/index.md           the /modules index
  _data/modules.yml          nav + index data

A module without a docs.md produces no page and no data entry.
"""
import argparse
import json
import re
import sys
from pathlib import Path
from typing import NoReturn

AREAS = ("agentic", "tools", "harnesses")
AREA_LABELS = {"agentic": "Agentic", "tools": "Tools", "harnesses": "Harnesses"}
CAPABILITY_KEYS = ("agents", "commands", "skills", "hooks", "plugins", "tools", "mcps")
# (row label, singular, plural) per capability kind.
CAPABILITY_LABELS = {
    "agents": ("Agent", "agent", "agents"),
    "commands": ("Command", "command", "commands"),
    "skills": ("Skill", "skill", "skills"),
    "hooks": ("Hook", "hook", "hooks"),
    "plugins": ("Plugin", "plugin", "plugins"),
    "tools": ("Tool", "tool", "tools"),
    "mcps": ("MCP", "MCP", "MCPs"),
}
FM_LINE = re.compile(r"^([A-Za-z0-9_-]+):\s?(.*)$")
GENERATED_NOTE = "<!-- Generated by gather-module-docs — do not edit. -->"


def _error(msg) -> NoReturn:
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def _unquote(value):
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    return value


def _parse_value(raw):
    """A scalar, or a YAML flow list (`[a, b]`)."""
    raw = raw.strip()
    if raw.startswith("[") and raw.endswith("]"):
        inner = raw[1:-1].strip()
        return [_unquote(item) for item in inner.split(",")] if inner else []
    return _unquote(raw)


def _as_list(value):
    if isinstance(value, dict):
        return list(value.keys())
    if isinstance(value, list):
        return value
    return [value] if value else []


def bare_name(name):
    return name.split(":", 1)[1] if ":" in name else name


def read_scalar(path, key):
    """Read one scalar from a file's front matter; None when absent."""
    pattern = re.compile(r"^" + re.escape(key) + r":\s*(.*)$")
    try:
        with path.open(encoding="utf-8") as handle:
            for _ in range(25):
                line = handle.readline()
                if not line:
                    break
                match = pattern.match(line.strip())
                if match:
                    return _unquote(match.group(1))
    except OSError:
        pass
    return None


def read_json(path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


def capability_entries(meta, kind):
    """(names, purpose overrides) declared for one capability kind.

    A list declares names only (purposes are derived from the module files);
    a map declares names and their purpose.
    """
    value = meta.get(kind)
    if isinstance(value, dict):
        return list(value.keys()), value
    return _as_list(value), {}


def capability_details(root, area, name, meta):
    """Derive each capability's purpose from the module's own files."""
    base = root / "src" / area / name
    details = {kind: {} for kind in CAPABILITY_KEYS}

    skill_files = sorted(base.glob("skills/*/SKILL.md")) + sorted(base.glob("skills/SKILL.md"))
    for skill_md in skill_files:
        skill_name = read_scalar(skill_md, "name") or skill_md.parent.name
        details["skills"][bare_name(skill_name)] = read_scalar(skill_md, "description") or ""

    for agent_md in sorted(base.glob("agents/*.md")):
        details["agents"][agent_md.stem.lower()] = read_scalar(agent_md, "description") or ""
    for command_md in sorted(base.glob("commands/*.md")):
        details["commands"][command_md.stem] = read_scalar(command_md, "description") or ""

    for hook in (read_json(base / "hooks.json") or {}).get("hooks", []):
        if hook.get("id"):
            details["hooks"][hook["id"]] = hook.get("event", "")

    for server in (read_json(base / "mcp.json") or {}).get("mcp", {}):
        details["mcps"][server] = ""

    if (base / "tools").is_dir():
        for tool in sorted((base / "tools").iterdir()):
            if tool.is_file():
                details["tools"][tool.name.split(".")[0]] = ""

    plugins = read_json(base / "plugin.opencode.json")
    if isinstance(plugins, (list, dict)):
        for plugin in plugins:
            if isinstance(plugin, str):
                details["plugins"][plugin] = ""

    return details


def capability_summary(capabilities):
    parts = []
    for kind in CAPABILITY_KEYS:
        count = len(capabilities.get(kind, []))
        if not count:
            continue
        _, singular, plural = CAPABILITY_LABELS[kind]
        parts.append(f"{count} {singular if count == 1 else plural}")
    return " · ".join(parts)


def render_contents(module):
    capabilities = module.get("capabilities") or {}
    overrides = module.get("overrides") or {}
    details = module.get("details") or {}
    rows = []
    for kind in CAPABILITY_KEYS:
        label = CAPABILITY_LABELS[kind][0]
        for name in capabilities.get(kind, []):
            purpose = (
                overrides.get(kind, {}).get(name)
                or details.get(kind, {}).get(bare_name(name))
                or ""
            )
            rows.append(f"| {label} | `{name}` | {purpose} |")
    if not rows:
        return ""
    header = ["## Contents", "", "| Type | Name | Purpose |", "| --- | --- | --- |"]
    return "\n".join(header + rows) + "\n"


def insert_contents(body, section):
    if not section:
        return body
    match = re.search(r"^##\s+Configuration\s*$", body, re.MULTILINE)
    if match:
        return body[: match.start()] + section + "\n" + body[match.start():]
    return body.rstrip() + "\n\n" + section


def parse_front_matter(text, path):
    """Minimal top-level `key: value` parser with one level of nesting."""
    if not text.startswith("---"):
        return {}, text
    parts = text.split("---", 2)
    if len(parts) < 3:
        _error(f"{path}: malformed front matter (missing closing ---)")

    meta, block = {}, None
    for raw in parts[1].splitlines():
        if not raw.strip():
            continue
        if raw[0] in " \t":
            if block:
                match = FM_LINE.match(raw.strip())
                if match:
                    meta[block][match.group(1)] = _parse_value(match.group(2))
            continue
        match = FM_LINE.match(raw)
        if not match:
            continue
        key, value = match.group(1), match.group(2)
        if value == "":
            block = key
            meta[key] = {}
        else:
            block = None
            meta[key] = _parse_value(value)
    return meta, parts[2].lstrip("\n")


def humanize(name):
    return name.replace("-", " ").replace("_", " ").title()


def yaml_string(value):
    # JSON strings are a valid subset of YAML strings — correct quoting for free.
    return json.dumps(value, ensure_ascii=False)


def collect(root):
    modules = []
    for area in AREAS:
        area_dir = root / "src" / area
        if not area_dir.is_dir():
            continue
        for module_dir in sorted(p for p in area_dir.iterdir() if p.is_dir()):
            doc = module_dir / "docs.md"
            if not doc.is_file():
                continue
            meta, body = parse_front_matter(doc.read_text(encoding="utf-8"), doc)
            description = meta.get("description")
            if not description:
                _error(f"{doc}: missing required 'description' front matter")
            capabilities, overrides = {}, {}
            for key in CAPABILITY_KEYS:
                names, purposes = capability_entries(meta, key)
                if names:
                    capabilities[key] = names
                    if purposes:
                        overrides[key] = purposes
            modules.append({
                "name": module_dir.name,
                "area": area,
                "area_label": AREA_LABELS[area],
                "title": meta.get("title") or humanize(module_dir.name),
                "description": description,
                "url": f"/modules/{area}/{module_dir.name}",
                "capabilities": capabilities,
                "overrides": overrides,
                "details": capability_details(root, area, module_dir.name, meta),
                "summary": capability_summary(capabilities),
                "body": body.rstrip() + "\n",
            })
    return modules


def render_page(module):
    front = [
        "---",
        "layout: page",
        f"title: {yaml_string(module['title'])}",
        f"description: {yaml_string(module['description'])}",
        "nav_section: docs",
        f"module_name: {module['name']}",
        f"module_area: {module['area']}",
        f"module_area_label: {yaml_string(module['area_label'])}",
    ]
    if module.get("summary"):
        front.append(f"capability_summary: {yaml_string(module['summary'])}")
    front.append("---")
    body = insert_contents(module["body"], render_contents(module))
    return "\n".join(front) + f"\n\n{GENERATED_NOTE}\n\n{body}"


def render_index(modules):
    counts = {area: [m for m in modules if m["area"] == area] for area in AREAS}
    jump = " · ".join(
        f"[{AREA_LABELS[area]} ({len(counts[area])})](#{area})"
        for area in AREAS
        if counts[area]
    )

    rows = [jump, ""]
    for area in AREAS:
        area_modules = sorted(counts[area], key=lambda m: m["name"])
        if not area_modules:
            continue
        rows.append(f"## {AREA_LABELS[area]}\n")
        rows.append("| Module | Description | Contains |")
        rows.append("| ------ | ----------- | -------- |")
        for module in area_modules:
            link = "{{ '" + module["url"] + "' | relative_url }}"
            rows.append(
                f"| [{module['title']}]({link}) | {module['description']}"
                f" | {module.get('summary') or '—'} |"
            )
        rows.append("")

    front = "\n".join([
        "---",
        "layout: page",
        'title: "Modules"',
        'description: "Every documented DevBot module."',
        "nav_section: docs",
        "nav_modules: true",
        "---",
    ])
    return f"{front}\n\n{GENERATED_NOTE}\n\n" + "\n".join(rows)


def render_data(modules):
    lines = ["# Generated by gather-module-docs — do not edit."]
    for module in modules:
        lines.append(f"- name: {yaml_string(module['name'])}")
        lines.append(f"  area: {yaml_string(module['area'])}")
        lines.append(f"  title: {yaml_string(module['title'])}")
        lines.append(f"  description: {yaml_string(module['description'])}")
        lines.append(f"  url: {yaml_string(module['url'])}")
        capabilities = module.get("capabilities") or {}
        if capabilities:
            lines.append("  capabilities:")
            for key in CAPABILITY_KEYS:
                if not capabilities.get(key):
                    continue
                lines.append(f"    {key}:")
                for item in capabilities[key]:
                    lines.append(f"      - {yaml_string(item)}")
    return "\n".join(lines) + "\n"


def prune(pages_dir, written):
    if not pages_dir.is_dir():
        return
    for stale in pages_dir.rglob("*.md"):
        if stale.resolve() not in written:
            stale.unlink()
    for directory in sorted(
        (p for p in pages_dir.rglob("*") if p.is_dir()), reverse=True
    ):
        if not any(directory.iterdir()):
            directory.rmdir()


def default_root():
    for parent in Path(__file__).resolve().parents:
        if (parent / "src" / "agentic").is_dir():
            return parent
    _error("could not locate the repo root — pass --root")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", help="repo root (default: auto-detected)")
    parser.add_argument("--out", help="site source dir (default: <root>/docs)")
    args = parser.parse_args()

    root = Path(args.root).resolve() if args.root else default_root()
    out = Path(args.out).resolve() if args.out else root / "docs"

    modules = collect(root)
    if not modules:
        print(
            "WARN: no module docs.md found under src/{agentic,tools,harnesses}/",
            file=sys.stderr,
        )

    written = set()
    for module in modules:
        page = out / "modules" / module["area"] / f"{module['name']}.md"
        page.parent.mkdir(parents=True, exist_ok=True)
        page.write_text(render_page(module), encoding="utf-8")
        written.add(page.resolve())

    index = out / "modules" / "index.md"
    index.parent.mkdir(parents=True, exist_ok=True)
    index.write_text(render_index(modules), encoding="utf-8")
    written.add(index.resolve())

    data = out / "_data" / "modules.yml"
    data.parent.mkdir(parents=True, exist_ok=True)
    data.write_text(render_data(modules), encoding="utf-8")

    prune(out / "modules", written)
    print(f"gathered {len(modules)} module docs into {out}")


if __name__ == "__main__":
    main()
