#!/usr/bin/env python3
"""Gather per-module docs.md into the Jekyll site.

Walks src/{agentic,tools,harnesses}/<module>/docs.md and emits, into the site
source directory:

  modules/<area>/<name>.md   one page per module that has a docs.md
  modules/index.md           the /modules index
  _data/modules.yml          nav + index data

A module without a docs.md produces no page and no data entry.
"""
import argparse
import json
import re
import sys
from pathlib import Path
from typing import NoReturn

AREAS = ("agentic", "tools", "harnesses")
AREA_LABELS = {"agentic": "Modules", "tools": "Tools &amp; Services", "harnesses": "Harnesses"}
FM_LINE = re.compile(r"^([A-Za-z0-9_-]+):\s?(.*)$")
GENERATED_NOTE = "<!-- Generated by gather-module-docs — do not edit. -->"


def _error(msg) -> NoReturn:
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def _unquote(value):
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    return value


def parse_front_matter(text, path):
    """Minimal top-level `key: value` parser with one level of nesting."""
    if not text.startswith("---"):
        return {}, text
    parts = text.split("---", 2)
    if len(parts) < 3:
        _error(f"{path}: malformed front matter (missing closing ---)")

    meta, block = {}, None
    for raw in parts[1].splitlines():
        if not raw.strip():
            continue
        if raw[0] in " \t":
            if block:
                match = FM_LINE.match(raw.strip())
                if match:
                    meta[block][match.group(1)] = _unquote(match.group(2))
            continue
        match = FM_LINE.match(raw)
        if not match:
            continue
        key, value = match.group(1), match.group(2)
        if value == "":
            block = key
            meta[key] = {}
        else:
            block = None
            meta[key] = _unquote(value)
    return meta, parts[2].lstrip("\n")


def humanize(name):
    return name.replace("-", " ").replace("_", " ").title()


def yaml_string(value):
    # JSON strings are a valid subset of YAML strings — correct quoting for free.
    return json.dumps(value)


def collect(root):
    modules = []
    for area in AREAS:
        area_dir = root / "src" / area
        if not area_dir.is_dir():
            continue
        for module_dir in sorted(p for p in area_dir.iterdir() if p.is_dir()):
            doc = module_dir / "docs.md"
            if not doc.is_file():
                continue
            meta, body = parse_front_matter(doc.read_text(encoding="utf-8"), doc)
            description = meta.get("description")
            if not description:
                _error(f"{doc}: missing required 'description' front matter")
            modules.append({
                "name": module_dir.name,
                "area": area,
                "title": meta.get("title") or humanize(module_dir.name),
                "description": description,
                "url": f"/modules/{area}/{module_dir.name}",
                "body": body.rstrip() + "\n",
            })
    return modules


def render_page(module):
    front = "\n".join([
        "---",
        "layout: page",
        f"title: {yaml_string(module['title'])}",
        f"description: {yaml_string(module['description'])}",
        "nav_section: docs",
        f"module_name: {module['name']}",
        f"module_area: {module['area']}",
        "---",
    ])
    return f"{front}\n\n{GENERATED_NOTE}\n\n{module['body']}"


def render_index(modules):
    rows = []
    for area in AREAS:
        area_modules = sorted(
            (m for m in modules if m["area"] == area), key=lambda m: m["name"]
        )
        if not area_modules:
            continue
        rows.append(f"## {AREA_LABELS[area]}\n")
        rows.append("| Module | Description |")
        rows.append("| ------ | ----------- |")
        for module in area_modules:
            link = "{{ '" + module["url"] + "' | relative_url }}"
            rows.append(f"| [{module['title']}]({link}) | {module['description']} |")
        rows.append("")
    front = "\n".join([
        "---",
        "layout: page",
        'title: "Modules"',
        'description: "Every documented DevBot module."',
        "nav_section: docs",
        "---",
    ])
    return f"{front}\n\n{GENERATED_NOTE}\n\n" + "\n".join(rows)


def render_data(modules):
    lines = ["# Generated by gather-module-docs — do not edit."]
    for module in modules:
        lines.append(f"- name: {yaml_string(module['name'])}")
        lines.append(f"  area: {yaml_string(module['area'])}")
        lines.append(f"  title: {yaml_string(module['title'])}")
        lines.append(f"  description: {yaml_string(module['description'])}")
        lines.append(f"  url: {yaml_string(module['url'])}")
    return "\n".join(lines) + "\n"


def prune(pages_dir, written):
    if not pages_dir.is_dir():
        return
    for stale in pages_dir.rglob("*.md"):
        if stale.resolve() not in written:
            stale.unlink()
    for directory in sorted(
        (p for p in pages_dir.rglob("*") if p.is_dir()), reverse=True
    ):
        if not any(directory.iterdir()):
            directory.rmdir()


def default_root():
    for parent in Path(__file__).resolve().parents:
        if (parent / "src" / "agentic").is_dir():
            return parent
    _error("could not locate the repo root — pass --root")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", help="repo root (default: auto-detected)")
    parser.add_argument("--out", help="site source dir (default: <root>/docs)")
    args = parser.parse_args()

    root = Path(args.root).resolve() if args.root else default_root()
    out = Path(args.out).resolve() if args.out else root / "docs"

    modules = collect(root)
    if not modules:
        print(
            "WARN: no module docs.md found under src/{agentic,tools,harnesses}/",
            file=sys.stderr,
        )

    written = set()
    for module in modules:
        page = out / "modules" / module["area"] / f"{module['name']}.md"
        page.parent.mkdir(parents=True, exist_ok=True)
        page.write_text(render_page(module), encoding="utf-8")
        written.add(page.resolve())

    index = out / "modules" / "index.md"
    index.parent.mkdir(parents=True, exist_ok=True)
    index.write_text(render_index(modules), encoding="utf-8")
    written.add(index.resolve())

    data = out / "_data" / "modules.yml"
    data.parent.mkdir(parents=True, exist_ok=True)
    data.write_text(render_data(modules), encoding="utf-8")

    prune(out / "modules", written)
    print(f"gathered {len(modules)} module docs into {out}")


if __name__ == "__main__":
    main()
